### ISSUE TITLE
screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(100)).takeScreenshot(driver); thorws exception

### ISSUE THREAD

**Issue by apathan123** [pazone/ashot#107]
Hi
I am using chrome and with below code it is throwing an exception Below is the trace of teh error I get in debug mode. 

screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(100)).takeScreenshot(driver);

Throws....
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at ru.yandex.qatools.ashot.util.InnerScript.execute(InnerScript.java:27)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getFullHeight(ViewportPastingDecorator.java:67)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:41)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)
	at Posttradesanity.Manualupload.imagecomparefunc(Manualupload.java:102)
	at Posttradesanity.Manualupload.upload(Manualupload.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by fescobar** [comment]
@apathan123 that is a problem with your dependencies. Try to add the dependency where is org.apache.commons.io.IOUtils

**Comment by apathan123** [comment]
This is sorted ..Thanks

**Comment by PanktiDShah** [comment]
Hello,

I am using following code;
Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);

I am getting exception;
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

I have added following required dependency;
<dependency>
    	<groupId>commons-io</groupId>
    	<artifactId>commons-io</artifactId>
    	<version>2.6</version>
</dependency>

Can you please help me to resolve this? Thanks

**Comment by fescobar** [comment]
Try with this or share a small version of your project
```
<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.7</version>
</dependency>
```

**Comment by PanktiDShah** [comment]
I tried updating with above dependency but I am still seeing the same issue. I am adding the method I am using to capture screenshot and TestNG trace. 
Can you please review the same? Also let me know if more details are required. Thanks


**Method**
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;


import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;
public static String captureScreenshot(WebDriver driver,String screenshotName)
	{	
		String errorFilePath = null;
		try 
		{	
			
			String timestamp = new SimpleDateFormat("MM_dd_yyyy__hh_mm_ss").format(new Date());	
			
			Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);
			BufferedImage Image = screenshot.getImage();
			File dest = new File(workingDir + "\\src\\Reports\\Failed Case Screenshots\\ "+screenshotName + "_" + timestamp+".png");
		    ImageIO.write(Image,"PNG",dest);
		    errorFilePath = dest.getAbsolutePath();
			System.out.println("Screenshot Captured");
			return errorFilePath;
			
		} 
		catch (Exception e)
		{
	 
			System.out.println("Exception while taking screenshot "+e.getMessage());
		}
		return errorFilePath;
	}

**TestNG trace**
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at ru.yandex.qatools.ashot.util.InnerScript.execute(InnerScript.java:27)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getFullHeight(ViewportPastingDecorator.java:67)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:41)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)
	at com.base.BaseClass.captureScreenshot(BaseClass.java:125)
	at com.amplifund.verification.AdminSysSecurityUsersPageVerification.verifyUserCreate(AdminSysSecurityUsersPageVerification.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by fescobar** [comment]
I need the project to check everything in my machine. Otherwise, it's not easy to help you @ PanktiDShah

**Comment by PanktiDShah** [comment]
Thank you so much @fescobar for your help. I am not allowed to share project due to security reasons. 

However; I will try and check other dependencies and keep you posted here if I find something. Thanks again for your time.

**Comment by fescobar** [comment]
@PanktiDShah Try with `mvn dependency:tree -Dverbose` maybe can help you to find the miss dependency.

**Comment by sreekar878** [comment]
can someone help me with this -- 
Code : 

   driver.findElement(By.id("Opportunity_Tab")).click();
	     Thread.sleep(2000);
	     **Screenshot s=new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);**
	     try {
			ImageIO.write(s.getImage(),"PNG",new File(path+"screenhot1.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

Error at Bold text

Exception in thread "Thread-8" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
        at ru.yandex.qatools.ashot.util.InnerScript.execute(InnerScript.java:27)
        at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getFullHeight(ViewportPastingDecorator.java:67)
        at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:41)
        at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
        at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)
        at com.slf.pdfConverterEngine.services.DownloadBoxFilesService.TakeScreenShots(DownloadBoxFilesService.java:580)
        at com.slf.pdfConverterEngine.services.DownloadBoxFilesService.recursiveDownloadMethod(DownloadBoxFilesService.java:191)
        at com.slf.pdfConverterEngine.controllers.PdfConverterEngineController$1.run(PdfConverterEngineController.java:42)


Using  dependencies  -

 <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.4</version>
    </dependency>

   <dependency>
			     <groupId>ru.yandex.qatools.ashot</groupId>
			     <artifactId>ashot</artifactId>
			     <version>1.5.4</version>
		</dependency>

**Comment by valfirst** [comment]
> Exception in thread "Thread-8" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

@sreekar878 the error means that either you use the invalid version of `commons-io` dependency or the dependency is not present in the classpath

**Comment by sreekar878** [comment]
@valfirst  Hey, can you help me with the correct version of commons-io or steps u feel I would have missed in setting the classpath for the dependency.

Thanks in advance.
