### ISSUE TITLE
Gson exception "not such method" :: installation guide improving 

### ISSUE THREAD

**Issue by ksiv** [pazone/ashot#122]
Ашот 1.5.2
Have not been working without:

>       <dependency>
>            <groupId>com.google.code.gson</groupId>
>           <artifactId>gson</artifactId>
>            <version>2.8.2</version>
>        </dependency>

****
java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;
	at org.openqa.selenium.json.Json.<clinit>(Json.java:35)
	at org.openqa.selenium.logging.profiler.HttpProfilerLogEntry.constructMessage(HttpProfilerLogEntry.java:37)
	at org.openqa.selenium.logging.profiler.HttpProfilerLogEntry.<init>(HttpProfilerLogEntry.java:29)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:135)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at com.epam.jdi.uitests.web.selenium.driver.SeleniumDriverFactory.lambda$registerDriver$0(SeleniumDriverFactory.java:198)
	at com.epam.jdi.uitests.web.selenium.driver.SeleniumDriverFactory.getDriver(SeleniumDriverFactory.java:371)
	at com.epam.jdi.uitests.web.selenium.driver.SeleniumDriverFactory.getDriver(SeleniumDriverFactory.java:324)
	at com.epam.jdi.uitests.web.settings.WebSettings.getDriver(WebSettings.java:76)
	at org.mytests.tests.steps.projectname.ui.Steps.setUp(Steps.java:109)

At row 109 : 
        String session = ((RemoteWebDriver) WebSettings.getDriver()).getSessionId().toString();

*****

after adding the dependence above no errors at this stage

**Comment by Debanjan-B** [comment]
Downloading and adding `gson-2.8.5.jar` solved the issue.
