### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/Matcher

### ISSUE THREAD

**Issue by dipakbachhav** [pazone/ashot#123]
Getting issue while comparing two images. Actually, when two images are different in that case I was expecting my assertion should be failed and print my error message like Images are different but at the moment facing issue: 

Code : 
```

	BufferedImage expectedImage = ImageIO.read(new File("C:\\Users\\user\\Desktop\\facseshape.gif"));
   
    BufferedImage actualImage = ImageIO.read(new File("C:\\Users\\user\\Desktop\\olivia-wilde-square-face.jpg"));
           
    System.out.println(expectedImage);
    System.out.println(actualImage);
    ImageDiffer imgDiff = new ImageDiffer();
    ImageDiff diff = imgDiff.makeDiff(actualImage, expectedImage);
    if(diff.hasDiff())
    {
    	System.out.println("not same");
    }
    else{
    	System.out.println("Same");
    }
```
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/Matcher
	at ru.yandex.qatools.ashot.comparison.ImageDiffer.hasDiffInChannel(ImageDiffer.java:92)
	at ru.yandex.qatools.ashot.comparison.ImageDiffer.markDiffPoints(ImageDiffer.java:80)
	at ru.yandex.qatools.ashot.comparison.ImageDiffer.makeDiff(ImageDiffer.java:57)
	at ru.yandex.qatools.ashot.comparison.ImageDiffer.makeDiff(ImageDiffer.java:96)
	at test.main(test.java:24)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

```

**Comment by sudheermudumala** [comment]
any update on this one. I am also getting same error

**Comment by miscsuresh** [comment]
I am also facing the same issue

**Comment by rahulkumarVassar** [comment]
any solution?

**Comment by valfirst** [comment]
> Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher

This error means that Hamcrest library dependency is not in the classpath, you should add missing dependency to fix the issue
