### ISSUE TITLE
page_dimensions.js does not work on IE

### ISSUE THREAD

**Issue by tmshft** [pazone/ashot#182]
Hi.

`ViewportPastingDecorator.getScreenshot`does not work on IE.

I think it is caused by  javascript error on IE.

```
// stacktrace:
java.lang.RuntimeException: org.openqa.selenium.JavascriptException: Error executing JavaScript
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
...
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {...}
Session ID: xxxxxx
	at pazone.ashot.util.InnerScript.execute(InnerScript.java:28)
	at pazone.ashot.ViewportPastingDecorator.getPageDimensions(ViewportPastingDecorator.java:69)
	at pazone.ashot.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:43)
	at pazone.ashot.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:37)
	at pazone.ashot.AShot.takeScreenshot(AShot.java:141)
	at jp.shiftinc.automation.util.ImageUtils.getScreenshot(ImageUtils.java:115)
```

On `page_dimensions.js` , below code makes a Javascript Error.
```
return {pageHeight, viewportHeight, viewportWidth}
```

and this code works correctly.
```
return {"pageHeight":pageHeight, "viewportHeight":viewportHeight, "viewportWidth":viewportWidth}
```

I hope that you may fix it and release ver 1.6.0.

## Environment

aShot:SNAPSHOT-1.6.0
OS:Windows10
Browser:IE11
Java:AdoptOpenJDK1.8.0.222
Selenium:3.14.15xx

**Comment by tmshft** [comment]
@pazone @valfirst 
great thx!!
