### ISSUE TITLE
Ashot is not working at all!

### ISSUE THREAD

**Issue by tlytvyn** [pazone/ashot#9]
I have added maven dependency and injected Ashot to my code for selenium tests, but it is not working at all.
I was trying screenshot of whole page, screenshots of separate leements.
I receive such error after executin mvn clean test:

demoTest(framework.utils.tests.WebDriverDemoTest)  Time elapsed: 16.161 sec  <<<
 FAILURE!
org.openqa.selenium.WebDriverException: $ is not defined
Command duration or timeout: 1.04 seconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43a
d8', time: '2014-10-23 13:11:40'
System info: host: 'CP0528', ip: '172.25.113.47', os.name: 'Windows 7', os.arch:
 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: 49c82632-7ae3-4066-b813-d5c263ae6c05
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cs
sSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts
=true, nativeEvents=true, webStorageEnabled=true, rotatable=false, locationConte
xtEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=33.0
.2}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

```
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
```

orAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.
java:204)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHa
ndler.java:156)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:599)
        at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDri
ver.java:508)
        at ru.yandex.qatools.ashot.util.JsCoords.findCoordsWithJquery(JsCoords.j
ava:26)
        at ru.yandex.qatools.ashot.coordinates.JqueryCoordsProvider.ofElement(Jq
ueryCoordsProvider.java:13)
        at ru.yandex.qatools.ashot.coordinates.CoordsProvider.ofElements(CoordsP
rovider.java:20)
        at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:110)
        at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:127)
        at framework.utils.tests.WebDriverDemoTest.searchGoogleEleks(WebDriverDe
moTest.java:65)
        at framework.utils.tests.WebDriverDemoTest.demoTest(WebDriverDemoTest.ja
va:49)
Caused by: org.openqa.selenium.WebDriverException: $ is not defined
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43a
d8', time: '2014-10-23 13:11:40'
System info: host: 'CP0528', ip: '172.25.113.47', os.name: 'Windows 7', os.arch:
 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Driver info: driver.version: unknown
        at <anonymous class>.anonymous(https://www.google.com.ua/?gfe_rd=cr&ei=7
I1XVKGaLaaH8Qfo-oHIAw&gws_rd=ssl#q=eleks line 68 > Function:19:10)
        at <anonymous class>.handleEvaluateEvent(https://www.google.com.ua/?gfe_
rd=cr&ei=7I1XVKGaLaaH8Qfo-oHIAw&gws_rd=ssl#q=eleks:68:20)

**Comment by MollyWing** [comment]
I am testing some pages where jQuery is running in no conflict mode.  coordsProvider is a good work-around for now, but this prevents our team from using a shared code-base.  I think it would be nice to see if we can find a fix for this issue.

**Comment by pazone** [comment]
@MollyWing Do you mean that `WebDriverCoordsProvider` should be default?

**Comment by MollyWing** [comment]
@pazone I think we shouldn't assume jQuery is available

**Comment by pazone** [comment]
@MollyWing Good idea. Thanks.
